// <auto-generated />
using System;
using CodeWithMena.PerfumeShop.DAL.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeWithMena.PerfumeShop.DAL.Persistence.Data.Migrations
{
    [DbContext(typeof(PerfumesShopDbContext))]
    [Migration("20251110204301_CreateDBAndPerfumeOilsTable")]
    partial class CreateDBAndPerfumeOilsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeWithMena.PerfumeShop.DAL.Entities.PerfumeOil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FragranceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FragrancyFamily")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETUTCDate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RatingOfSale")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PerfumeOils");
                });

            modelBuilder.Entity("CodeWithMena.PerfumeShop.DAL.Entities.PerfumeOil", b =>
                {
                    b.OwnsOne("CodeWithMena.PerfumeShop.DAL.Common.Entities.BasePerfumePrice", "PerfumePrice", b1 =>
                        {
                            b1.Property<Guid>("PerfumeOilId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("SalePrice")
                                .HasPrecision(10, 3)
                                .HasColumnType("decimal(10,3)")
                                .HasColumnName("SalePrice");

                            b1.Property<decimal?>("SupplierPrice")
                                .HasPrecision(10, 3)
                                .HasColumnType("decimal(10,3)")
                                .HasColumnName("SupplierPrice");

                            b1.HasKey("PerfumeOilId");

                            b1.ToTable("PerfumeOils");

                            b1.WithOwner()
                                .HasForeignKey("PerfumeOilId");
                        });

                    b.Navigation("PerfumePrice");
                });
#pragma warning restore 612, 618
        }
    }
}
